apiVersion: apps/v1
kind: Deployment
metadata:
  name: spdj-app
spec:
  selector:
    matchLabels:
      app: spdj-app
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: spdj-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: In
                values:
                - ap-northeast-2a
      terminationGracePeriodSeconds: 30
      containers:
      - image: camouflage129/spdj-app:0.1.4
        imagePullPolicy: Always
        name: spdj-app
        ports:
        - containerPort: 9000
        livenessProbe:
          failureThreshold: 3
          exec:
            command:
            - sh
            - -c
            - curl --silent http://localhost:9000/sys/healthz | grep -q '^{\"status\"\:\"UP\".*}$'
            - echo $?
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 1
        volumeMounts:
        - name: logs-persistent-storage
          mountPath: /logs
      volumes:
      - name: logs-persistent-storage
        persistentVolumeClaim:
          claimName: spdj-app-pvc
