kind: PersistentVolume
apiVersion: v1
metadata:
  name: spdj-app-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: logs
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/logs"
