apiVersion: v1
kind: Service
metadata:
  labels:
    app: spdj-app
    service: spdj-app
  name: spdj-app
spec:
  ports:
    - port: 80
      targetPort: 9000
      protocol: TCP
  type: NodePort
  selector:
    app: spdj-app
