kubectl delete -f ../spdj-mysql/service.yaml
kubectl delete -f ../spdj-mysql/deployment.yaml
kubectl delete -f ../spdj-mysql/pvc.yaml
kubectl delete -f ../spdj-mysql/pv.yaml
kubectl delete -f ../spdj-mysql/storageclass.yaml
kubectl delete -f ../spdj-app/service.yaml
kubectl delete -f ../spdj-app/deployment.yaml
kubectl delete -f ../spdj-app/pvc.yaml
kubectl delete -f ../spdj-app/pv.yaml
kubectl delete -f ../spdj-app/storageclass.yaml
kubectl delete -f ../nginx-ingress/deploy.yaml
kubectl delete -f ../nginx-ingress/ingress.yaml
