kind: PersistentVolume
apiVersion: v1
metadata:
  name: spdj-mysql-pv
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mysql
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/spdj/mysql"
